/* ============================================================
   Mobina 商品シード（編集データ）— 実在商品版
   ------------------------------------------------------------
   スペック・重量・価格は各メーカー公式 / 価格.com / レビュー等を元に
   2026年6月時点で調査した参考値。公開前に必ず最新の公式仕様で再確認すること。
   （特に MagGo Slim の重量、WF-1000XM5 の実売価格は変動・要確認）

   - 画像 / 現在価格 / レビュー平均・件数 / アフィリンク … fetch-products.mjs が楽天APIから取得
   - name / brand / weight / specs / tags / axes … この編集データを使用
   - rakutenKeyword … 楽天検索で当該商品を引くためのキー（itemCode指定がより確実）
   ============================================================ */

export default [
  /* ============ イヤホン ============ */
  {
    id: "ear-anker-liberty4nc", cat: "earphone",
    brand: "Anker / Soundcore", name: "Soundcore Liberty 4 NC",
    weight: 5.2, icon: "🎧",
    tags: ["ノイキャン", "防水", "ロングバッテリー"],
    specs: ["ウルトラANC 3.0", "LDAC対応(ハイレゾ)", "ケース込50h再生", "IPX4", "ワイヤレス充電"],
    axes: { cospa: 86, portability: 88, performance: 86, usability: 84, trust: 88 },
    pick: ["1万円台でウルトラANCとLDACまで入る完成度。価格と中身のバランスが良い", "ケース込50時間で電池持ちに余裕。週末の充電忘れでも安心", "ワイヤレス充電対応で普段使いの使い勝手が高い"],
    rakutenKeyword: "Anker Soundcore Liberty4 NC 完全ワイヤレスイヤホン",
  },
  {
    id: "ear-sony-wf1000xm5", cat: "earphone",
    brand: "Sony", name: "WF-1000XM5",
    weight: 5.9, icon: "🎧",
    tags: ["ノイキャン", "防水"],
    specs: ["業界最高クラスANC", "LDAC / LE Audio", "ケース込24h(ANC時)", "IPX4", "マルチポイント"],
    axes: { cospa: 60, portability: 80, performance: 96, usability: 86, trust: 92 },
    pick: ["ノイキャンの静寂さは頭一つ抜けたレベル。電車・飛行機で本領", "LDAC対応で音質も上位。高価だが満足度の高いフラッグシップ", "5.9gと軽量で、性能の割に装着負担が小さい"],
    rakutenKeyword: "ソニー WF-1000XM5 完全ワイヤレス",
  },
  {
    id: "ear-anker-p40i", cat: "earphone",
    brand: "Anker / Soundcore", name: "Soundcore P40i",
    weight: 5.0, icon: "🎧",
    tags: ["ノイキャン", "防水", "ロングバッテリー"],
    specs: ["ウルトラANC 2.0", "ケース込60h再生", "IPX5", "ワイヤレス充電", "マルチポイント"],
    axes: { cospa: 94, portability: 90, performance: 72, usability: 84, trust: 86 },
    pick: ["8000円前後でANC・ケース込60時間とコスパが突出", "ワイヤレス充電・マルチポイントまで入り機能不足を感じにくい", "初めてのノイキャンイヤホンに手堅い一台"],
    rakutenKeyword: "Anker Soundcore P40i",
  },
  {
    id: "ear-shokz-openfit2", cat: "earphone",
    brand: "Shokz", name: "OpenFit 2",
    weight: 9.4, icon: "🎧",
    tags: ["防水", "ロングバッテリー"],
    specs: ["オープンイヤー(耳を塞がない)", "ケース込48h再生", "IP55", "Bluetooth 5.4", "物理ボタン操作"],
    axes: { cospa: 66, portability: 70, performance: 78, usability: 90, trust: 84 },
    pick: ["耳をふさがないオープン型。ながら聴き・運動・在宅で活躍", "IP55で汗や雨に強く、ランニング用途に向く", "周囲の音が聞こえるので外出時の安全性が高い"],
    rakutenKeyword: "Shokz OpenFit2",
  },
  {
    id: "ear-earfun-airpro4", cat: "earphone",
    brand: "EarFun", name: "Air Pro 4",
    weight: 4.5, icon: "🎧",
    tags: ["ノイキャン", "防水", "ロングバッテリー"],
    specs: ["QuietSmart 3.0 ANC(-50dB)", "LDAC/aptX Lossless", "ケース込52h再生", "IPX5", "ワイヤレス充電"],
    axes: { cospa: 96, portability: 88, performance: 82, usability: 82, trust: 80 },
    pick: ["1万円以下とは思えないANC-50dBとLDAC対応。コスパ最強格", "ケース込52時間＋ワイヤレス充電で日常の隙が少ない", "とにかく安く高機能を狙うならまず候補"],
    rakutenKeyword: "EarFun Air Pro4 完全ワイヤレスイヤホン",
  },

  {
    id: "ear-soundpeats-air4pro", cat: "earphone",
    brand: "SOUNDPEATS", name: "Air4 Pro",
    weight: 4.7, icon: "🎧",
    tags: ["ノイキャン", "防水"],
    specs: ["アダプティブANC(-45dB)", "aptX Lossless/Snapdragon Sound", "ケース込26h再生", "マルチポイント"],
    axes: { cospa: 98, portability: 90, performance: 76, usability: 80, trust: 76 },
    pick: ["片側4.7gの軽さで長時間でも耳が疲れにくい", "8000円台でANC・マルチポイント・ロスレス対応と全部入り", "ワイヤレス充電は非対応。そこを割り切れるなら高コスパ"],
    rakutenKeyword: "SOUNDPEATS Air4 Pro",
  },

  /* ============ モバイルバッテリー / 充電器 ============ */
  {
    id: "bat-anker-fusion30", cat: "battery",
    brand: "Anker", name: "Power Bank (Fusion, 30W)",
    weight: 250, spec_value: 10000, icon: "🔋",
    tags: ["PD対応"],
    specs: ["10000mAh", "PD30W急速", "コンセント一体(プラグ内蔵)", "USB-Cケーブル一体", "PSE適合"],
    axes: { cospa: 84, portability: 56, performance: 88, usability: 96, trust: 88 },
    pick: ["コンセント・ケーブル・バッテリーが1台に。外出の荷物が減る", "PD30W急速充電対応で1台で完結させたい人向け", "250gとやや重め。携帯性より利便性を取った構成"],
    rakutenKeyword: "Anker Power Bank Fusion 10000mAh 30W コンセント一体",
  },
  {
    id: "bat-cio-smartcoby-slim", cat: "battery",
    brand: "CIO", name: "SMARTCOBY Pro SLIM 35W",
    weight: 180, spec_value: 10000, icon: "🔋",
    tags: ["PD対応", "薄型"],
    specs: ["10000mAh", "PD35W(PPS対応)", "厚さ約16mm", "3ポート(C×2/A×1)", "パススルー対応"],
    axes: { cospa: 90, portability: 84, performance: 86, usability: 84, trust: 82 },
    pick: ["厚さ16mm・180gで薄型と容量のバランスが良い国内ブランド", "PD35W・3ポートで複数機器を同時に充電できる", "パススルー対応で本体と機器をまとめて充電可能"],
    rakutenKeyword: "CIO SMARTCOBY Pro SLIM 35W 10000mAh",
  },
  {
    id: "bat-anker-nano-maggo-slim", cat: "battery",
    brand: "Anker", name: "Nano Power Bank (5000mAh, MagGo, Slim)",
    weight: 110, spec_value: 5000, icon: "🔋",
    tags: ["ワイヤレス充電", "軽量", "薄型"],
    specs: ["5000mAh", "Qi2 ワイヤレス15W", "厚さ約8.6mm(史上最薄)", "MagSafe対応", "有線20W入出力"],
    axes: { cospa: 80, portability: 96, performance: 70, usability: 90, trust: 86 },
    pick: ["厚さ8.6mm・110gでスマホに貼っても出っ張らない超軽量", "Qi2/MagSafeでケーブル不要。iPhoneユーザーに好相性", "容量は5000mAh＝スマホ約1回分。軽さ最優先の人向け"],
    rakutenKeyword: "Anker Nano Power Bank 5000mAh MagGo Slim",
  },
  {
    id: "bat-anker-powercore10000", cat: "battery",
    brand: "Anker", name: "PowerCore 10000",
    weight: 180, spec_value: 10000, icon: "🔋",
    tags: ["軽量"],
    specs: ["10000mAh", "約180gの軽量定番", "コンパクト設計", "USB-A出力", "PSE適合"],
    axes: { cospa: 92, portability: 86, performance: 58, usability: 80, trust: 88 },
    pick: ["約180gの軽量定番。価格も手頃で最初の1台に手堅い", "10000mAhでスマホ約2回分。普段使いに十分な容量", "USB-A中心で急速充電は控えめ。シンプル用途向け"],
    rakutenKeyword: "Anker PowerCore 10000",
  },
  {
    id: "bat-anker-737-24000", cat: "battery",
    brand: "Anker", name: "737 Power Bank (PowerCore 24000)",
    weight: 630, spec_value: 24000, icon: "🔋",
    tags: ["PD対応", "大容量"],
    specs: ["24000mAh", "最大140W出力", "ノートPC充電対応", "残量ディスプレイ搭載", "3ポート"],
    axes: { cospa: 78, portability: 30, performance: 96, usability: 82, trust: 86 },
    pick: ["24000mAh・140WでノートPCまで賄える大容量・高出力", "残量ディスプレイ搭載で管理しやすい。旅行・出張の相棒に", "630gと重いので毎日の持ち歩きより遠征向き"],
    rakutenKeyword: "Anker 737 Power Bank PowerCore 24000",
  },
  {
    id: "bat-elecom-de-c86-10000", cat: "battery",
    brand: "ELECOM", name: "半固体モバイルバッテリー DE-C86-10000BK",
    weight: 220, spec_value: 10000, icon: "🔋",   /* 公式仕様: 約220g（10000mAh/35W版） */
    tags: ["PD対応", "半固体電池"],
    specs: ["10000mAh", "半固体電池(高安全・長寿命)", "最大35W出力", "USB-C×2/A×1", "約2000回使用可"],
    axes: { cospa: 72, portability: 74, performance: 78, usability: 86, trust: 84 },
    pick: ["半固体電池採用で発火リスクを抑えた安全志向のモデル", "約2000回使用可と長寿命。長く使いたい人に向く", "10000mAh・35Wでスマホ・タブレットに十分。約220gで持ち歩きやすい"],
    rakutenKeyword: "エレコム 半固体モバイルバッテリー 10000mAh 35W",
  },
  /* ============ 2026年 現行モデル追加候補（メーカー公称値確認済み） ============ */
  {
    id: "ear-soundcore-liberty5", cat: "earphone",
    brand: "Anker / Soundcore", name: "Soundcore Liberty 5",
    weight: 5.2, icon: "🎧",
    tags: ["ノイキャン", "防水", "ロングバッテリー"],
    specs: ["ウルトラANC 3.5", "LDAC対応", "ケース込48h再生", "IP55", "ワイヤレス充電"],
    axes: { cospa: 90, portability: 88, performance: 90, usability: 90, trust: 90 },
    pick: ["Liberty 4 NCの後継。ANC・音質・防水を総合強化", "片耳5.2gで高機能機として軽量", "1万円台でLDAC・マルチポイント・ワイヤレス充電まで揃う"],
    rakutenKeyword: "Anker Soundcore Liberty5 完全ワイヤレスイヤホン",
  },
  {
    id: "ear-soundcore-liberty-buds", cat: "earphone",
    brand: "Anker / Soundcore", name: "Soundcore Liberty Buds",
    weight: 4.9, icon: "🎧",
    tags: ["ノイキャン", "防水"],
    specs: ["インナーイヤー型", "LDAC対応", "ケース込30h再生", "IP55", "マルチポイント"],
    axes: { cospa: 84, portability: 96, performance: 82, usability: 92, trust: 88 },
    pick: ["片耳4.9gで圧迫感を抑えたインナーイヤー型", "耳を密閉しない形状ながらANCを搭載", "長時間装着の軽さを優先する人向け"],
    rakutenKeyword: "Anker Soundcore Liberty Buds",
  },
  {
    id: "ear-sony-wf1000xm6", cat: "earphone",
    brand: "Sony", name: "WF-1000XM6",
    weight: 6.5, icon: "🎧",
    tags: ["ノイキャン", "防水"],
    specs: ["世界最高クラスANC", "LDAC対応", "ANC時ケース込24h", "IPX4", "8マイク"],
    axes: { cospa: 58, portability: 76, performance: 99, usability: 90, trust: 94 },
    pick: ["2026年のソニー最新フラッグシップ", "WF-1000XM5比でANCと通話品質を強化", "片耳6.5gで軽さより性能を優先するモデル"],
    rakutenKeyword: "ソニー WF-1000XM6 完全ワイヤレス",
  },
  {
    id: "bat-anker-nano-retractable-45w", cat: "battery",
    brand: "Anker", name: "Nano Power Bank (10000mAh, 45W, 巻取り式USB-Cケーブル)",
    weight: 230, spec_value: 10000, icon: "🔋",
    tags: ["PD対応"],
    specs: ["10000mAh", "最大45W出力", "巻取り式USB-Cケーブル", "3ポート", "残量表示"],
    axes: { cospa: 84, portability: 72, performance: 92, usability: 96, trust: 90 },
    pick: ["約70cmの巻取り式ケーブルで忘れ物を減らせる", "45W出力でスマホから小型PCまで対応", "230gなので軽さよりケーブル一体の便利さを重視"],
    rakutenKeyword: "Anker Nano Power Bank 10000mAh 45W 巻取り式 USB-Cケーブル",
  },
  {
    id: "gan-cio-novaport-solo2-65w", cat: "gan",
    brand: "CIO", name: "NovaPort SOLO II 65W",
    weight: 74, spec_value: 65, icon: "⚡",
    tags: ["PD対応", "折りたたみ"],
    specs: ["最大65W", "USB-C×1", "GaN", "折りたたみプラグ", "NovaSafety 2.0"],
    axes: { cospa: 88, portability: 96, performance: 90, usability: 82, trust: 88 },
    pick: ["65Wで約74g、0.88W/gの高い軽さ効率", "ノートPC用充電器を小型化したい人向け", "1ポート構成なので同時充電より携帯性を優先"],
    rakutenKeyword: "CIO NovaPort SOLO II 65W",
  },
  {
    id: "gan-anker-nano-45w", cat: "gan",
    brand: "Anker", name: "Nano Charger (45W)",
    weight: 60, spec_value: 45, icon: "⚡",
    tags: ["PD対応", "折りたたみ"],
    specs: ["最大45W", "USB-C×1", "折りたたみプラグ", "約60g"],
    axes: { cospa: 84, portability: 94, performance: 82, usability: 82, trust: 92 },
    pick: ["約60gでスマホから一部ノートPCまで充電", "単ポートで迷わず使える", "65Wが不要なら重量と価格を抑えやすい"],
    rakutenKeyword: "Anker Nano Charger 45W",
  },
  {
    id: "ssd-sandisk-slim-1tb", cat: "ssd",
    brand: "SanDisk", name: "Slim Portable SSD 1TB",
    weight: 17.1, spec_value: 1000, icon: "💾",
    tags: ["軽量"],
    specs: ["1TB", "最大読出420MB/s", "USB 3.2 Gen 1", "ケーブル不要", "3年保証"],
    axes: { cospa: 76, portability: 100, performance: 72, usability: 96, trust: 92 },
    pick: ["1TBで17.1g、58.5GB/gの突出した軽さ効率", "USB-Cへ直接挿せてケーブル不要", "速度より携帯性を最優先する人向け"],
    rakutenKeyword: "SanDisk Slim Portable SSD 1TB SDSSDE20-1T00",
  },
  {
    id: "ssd-sandisk-portable-1tb", cat: "ssd",
    brand: "SanDisk", name: "Portable SSD 1TB SDSSDE30",
    weight: 40, spec_value: 1000, icon: "💾",
    tags: [],
    specs: ["1TB", "最大読出800MB/s", "USB 3.2 Gen 2", "2m落下保護", "3年保証"],
    axes: { cospa: 84, portability: 94, performance: 84, usability: 88, trust: 92 },
    pick: ["40gで読出最大800MB/s、軽さと速度のバランス型", "最大2mの落下保護で持ち歩きに向く", "定番メーカーの保証を重視する人向け"],
    rakutenKeyword: "SanDisk Portable SSD 1TB SDSSDE30",
  },
  {
    id: "tag-mamorio-re", cat: "smarttag",
    brand: "MAMORIO", name: "MAMORIO RE",
    weight: 3.4, icon: "🏷️",
    tags: [],
    specs: ["3.4g", "電池交換式", "電池寿命約11か月", "Bluetooth", "MAMORIO Spot対応"],
    axes: { cospa: 74, portability: 100, performance: 76, usability: 86, trust: 88 },
    pick: ["わずか3.4gで鍵や財布に付けやすい", "電池交換式で本体を継続利用できる", "GPSではなくユーザーネットワーク型の紛失防止タグ"],
    rakutenKeyword: "MAMORIO RE 紛失防止タグ",
  },
];
